### ISSUE TITLE
migrations folder

### ISSUE THREAD

**Issue by medhatelmasry** [plan-your-vote/plan-your-vote-cms#84]
In the .gitignore file, migrations folder is ignored. This is not the way it is supposed to work.

Migrations folder should not be excluded from pushing into git. We need to ensure that seed data goes not get duplicated.

**Comment by ryanliang88** [comment]
Migrations folder should be uncommented. I'm not sure how exactly to deal with merge conflicts now that the folder has been included.

Aside: If anyone's looking at automatic migrations, that only exists in EF6.

**Comment by medhatelmasry** [comment]
Joey Tang confirmed that migrations folder not in .gitignore

**Comment by medhatelmasry** [comment]
No other problems left
