### ISSUE TITLE
Improve data seeding

### ISSUE THREAD

**Issue by medhatelmasry** [plan-your-vote/plan-your-vote-cms#85]
To seed candidates & polling places data, it is necessary to delete the entire database

On Azure: console >> rm PlanYourVote.db

Find an better way of seeing data.

Seeded data should be generic like: candidate1, candidate2, ...

Consider import functionality to load JSON data instead of code first seeding

**Comment by ryanliang88** [comment]
Consider different data format and tradeoffs i.e. CSVs (lines, Excel support) vs XML (verbose), system vs user data vs demo / test data, 

Currently seeding is coupled into the application startup and was intended for testing and demos. Removing it from the application startup is a necessary first step.

**Comment by medhatelmasry** [comment]
Joey Tang >> Moved candidates & polling places into onModelCreating method. Made data generic. Migrations are being used only for candidates & polling.

**Comment by medhatelmasry** [comment]
No more work to be done on this
